[2022-03-17 02:42:42,170] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2010-04-02T04:00:00+00:00 [queued]>
[2022-03-17 02:42:42,201] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2010-04-02T04:00:00+00:00 [queued]>
[2022-03-17 02:42:42,204] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 02:42:42,206] {taskinstance.py:1239} INFO - Starting attempt 3 of 3
[2022-03-17 02:42:42,210] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 02:42:42,230] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_pbp_data> on 2010-04-02 04:00:00+00:00
[2022-03-17 02:42:42,238] {standard_task_runner.py:52} INFO - Started process 225 to run task
[2022-03-17 02:42:42,243] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_bucket_ingestion_dag', 'get_pbp_data', 'scheduled__2010-04-02T04:00:00+00:00', '--job-id', '5989', '--raw', '--subdir', 'DAGS_FOLDER/pbp_ingestion_dag.py', '--cfg-path', '/tmp/tmpl8zge02f', '--error-file', '/tmp/tmpu6r4unoq']
[2022-03-17 02:42:42,245] {standard_task_runner.py:77} INFO - Job 5989: Subtask get_pbp_data
[2022-03-17 02:42:42,329] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2010-04-02T04:00:00+00:00 [running]> on host 0e12c27218bc
[2022-03-17 02:42:42,434] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_bucket_ingestion_dag
AIRFLOW_CTX_TASK_ID=get_pbp_data
AIRFLOW_CTX_EXECUTION_DATE=2010-04-02T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2010-04-02T04:00:00+00:00
[2022-03-17 02:43:22,679] {python.py:175} INFO - Done. Returned value was: None
[2022-03-17 02:43:22,697] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_bucket_ingestion_dag, task_id=get_pbp_data, execution_date=20100402T040000, start_date=20220317T024242, end_date=20220317T024322
[2022-03-17 02:43:22,732] {local_task_job.py:212} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-03-17 02:43:22,738] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 225. PIDs of all processes in the group: [225]
[2022-03-17 02:43:22,740] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 225
[2022-03-17 02:43:22,749] {process_utils.py:70} INFO - Process psutil.Process(pid=225, status='terminated', exitcode=0, started='02:42:42') (225) terminated with exit code 0
