[2022-03-18 04:46:40,836] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2010-03-07T04:00:00+00:00 [queued]>
[2022-03-18 04:46:40,907] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2010-03-07T04:00:00+00:00 [queued]>
[2022-03-18 04:46:40,911] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 04:46:40,913] {taskinstance.py:1239} INFO - Starting attempt 4 of 5
[2022-03-18 04:46:40,915] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 04:46:40,977] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_pbp_data> on 2010-03-07 04:00:00+00:00
[2022-03-18 04:46:40,986] {standard_task_runner.py:52} INFO - Started process 634 to run task
[2022-03-18 04:46:40,995] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_bucket_ingestion_dag', 'get_pbp_data', 'scheduled__2010-03-07T04:00:00+00:00', '--job-id', '6304', '--raw', '--subdir', 'DAGS_FOLDER/pbp_ingestion_dag.py', '--cfg-path', '/tmp/tmp1fep_98c', '--error-file', '/tmp/tmpc3nldtsq']
[2022-03-18 04:46:41,001] {standard_task_runner.py:77} INFO - Job 6304: Subtask get_pbp_data
[2022-03-18 04:46:46,139] {local_task_job.py:207} WARNING - Recorded pid 644 does not match the current pid 634
[2022-03-18 04:46:46,145] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 634. PIDs of all processes in the group: [634]
[2022-03-18 04:46:46,149] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 634
[2022-03-18 04:46:46,249] {process_utils.py:70} INFO - Process psutil.Process(pid=634, status='terminated', exitcode=0, started='04:46:40') (634) terminated with exit code 0
